apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signia-ingress
  namespace: signia
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: api.signia.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: signia-api
                port:
                  number: 80
    - host: console.signia.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: signia-console
                port:
                  number: 80
    - host: interface.signia.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: signia-interface
                port:
                  number: 80
